### ISSUE TITLE
Passing through invalid link crashes discord

### ISSUE THREAD

**Issue by EssenceofLuna** [VenPlugs/petpet#1]
If you pass through something invalid, such as a channel or server ID, crashes discord. Giving a user ID works fine but I also get a crash when I give it a PNG link, which might be a related issue.

**Comment by Vendicated** [comment]
that was a little flaw in my logic that i didn't catch during testing but noticed as soon as I released this plugin. I fixed it in https://github.com/VenPlugs/petpet/commit/b5f4d454bd15084d4ff86c02b26fd498e1e4bbe3

Thanks for the report :)
