### ISSUE TITLE
Broken. Yet again

### ISSUE THREAD

**Issue by xamionex** [VenPlugs/petpet#2]
Latest discord update broke it :(

### Expected behavior

.petpet @Vendicated 
sends gif

### Actual behavior

.petpet @Vendicated 
nothing happens

**Comment by Vendicated** [comment]
Fixed in https://github.com/VenPlugs/petpet/commit/f591cdc5b809c4d52c2666519571484517ac5c8d

**Comment by xamionex** [comment]
FUNNIEST FIX EVER.
